/******************************************************************************
 * @file ota_web_ui.h
 * @brief Embedded HTML/CSS/JavaScript for OTA web interface
 *
 * @details This file contains the complete web UI for firmware uploads,
 *          embedded as C string constants. The UI is served by the HTTP
 *          server and provides:
 *          - Drag-and-drop firmware file upload
 *          - Real-time upload progress bar
 *          - Status messages (verifying, flashing, success, errors)
 *          - Responsive design (works on mobile/desktop)
 *          - Modern, clean interface with minimal dependencies
 * 
 *          The HTML is self-contained (no external resources) to work
 *          offline and minimize flash usage.
 *
 ******************************************************************************/

#ifndef OTA_WEB_UI_H
#define OTA_WEB_UI_H

/*******************************************************************************/
/*                                 INCLUDES                                    */
/*******************************************************************************/

/*******************************************************************************/
/*                                  MACROS                                     */
/*******************************************************************************/

/*******************************************************************************/
/*                                DATA TYPES                                   */
/*******************************************************************************/

/*******************************************************************************/
/*                     GLOBAL VARIABLES DECLARATIONS                           */
/*******************************************************************************/

/**
 * @brief HTML page for OTA firmware upload interface
 * 
 * @details This is a single-page application that handles:
 *          1. File selection via drag-and-drop or file picker
 *          2. AJAX upload with progress tracking
 *          3. Real-time status updates during verification and flashing
 *          4. Error handling and user feedback
 * 
 *          The page uses vanilla JavaScript (no frameworks) to minimize size.
 *          Styling is inline CSS for simplicity.
 */
static const char OTA_HTML_PAGE[] = 
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>ESP32 OTA Update</title>\n"
"    <style>\n"
"        * { margin: 0; padding: 0; box-sizing: border-box; }\n"
"        body {\n"
"            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif;\n"
"            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n"
"            min-height: 100vh;\n"
"            display: flex;\n"
"            align-items: center;\n"
"            justify-content: center;\n"
"            padding: 20px;\n"
"        }\n"
"        .container {\n"
"            background: white;\n"
"            border-radius: 16px;\n"
"            box-shadow: 0 20px 60px rgba(0,0,0,0.3);\n"
"            max-width: 500px;\n"
"            width: 100%;\n"
"            padding: 40px;\n"
"        }\n"
"        h1 {\n"
"            color: #333;\n"
"            margin-bottom: 10px;\n"
"            font-size: 28px;\n"
"            text-align: center;\n"
"        }\n"
"        .subtitle {\n"
"            color: #666;\n"
"            text-align: center;\n"
"            margin-bottom: 30px;\n"
"            font-size: 14px;\n"
"        }\n"
"        .info-box {\n"
"            background: #f5f7fa;\n"
"            border-radius: 8px;\n"
"            padding: 15px;\n"
"            margin-bottom: 25px;\n"
"            font-size: 13px;\n"
"            color: #555;\n"
"        }\n"
"        .info-box strong { color: #333; }\n"
"        .upload-area {\n"
"            border: 2px dashed #cbd5e0;\n"
"            border-radius: 12px;\n"
"            padding: 50px 20px;\n"
"            text-align: center;\n"
"            cursor: pointer;\n"
"            transition: all 0.3s;\n"
"            margin-bottom: 20px;\n"
"        }\n"
"        .upload-area:hover {\n"
"            border-color: #667eea;\n"
"            background: #f7fafc;\n"
"        }\n"
"        .upload-area.dragover {\n"
"            border-color: #667eea;\n"
"            background: #eef2ff;\n"
"        }\n"
"        .upload-icon {\n"
"            font-size: 48px;\n"
"            margin-bottom: 15px;\n"
"        }\n"
"        .upload-text {\n"
"            color: #4a5568;\n"
"            font-size: 16px;\n"
"            margin-bottom: 8px;\n"
"        }\n"
"        .upload-hint {\n"
"            color: #a0aec0;\n"
"            font-size: 13px;\n"
"        }\n"
"        input[type=\"file\"] { display: none; }\n"
"        .btn {\n"
"            width: 100%;\n"
"            padding: 14px;\n"
"            background: #667eea;\n"
"            color: white;\n"
"            border: none;\n"
"            border-radius: 8px;\n"
"            font-size: 16px;\n"
"            font-weight: 600;\n"
"            cursor: pointer;\n"
"            transition: background 0.3s;\n"
"            margin-bottom: 15px;\n"
"        }\n"
"        .btn:hover { background: #5a67d8; }\n"
"        .btn:disabled {\n"
"            background: #cbd5e0;\n"
"            cursor: not-allowed;\n"
"        }\n"
"        .progress-container {\n"
"            display: none;\n"
"            margin-bottom: 20px;\n"
"        }\n"
"        .progress-bar-bg {\n"
"            width: 100%;\n"
"            height: 24px;\n"
"            background: #e2e8f0;\n"
"            border-radius: 12px;\n"
"            overflow: hidden;\n"
"        }\n"
"        .progress-bar {\n"
"            height: 100%;\n"
"            background: linear-gradient(90deg, #667eea 0%, #764ba2 100%);\n"
"            width: 0%;\n"
"            transition: width 0.3s;\n"
"            display: flex;\n"
"            align-items: center;\n"
"            justify-content: center;\n"
"            color: white;\n"
"            font-size: 12px;\n"
"            font-weight: 600;\n"
"        }\n"
"        .status {\n"
"            text-align: center;\n"
"            padding: 12px;\n"
"            border-radius: 8px;\n"
"            font-size: 14px;\n"
"            margin-bottom: 15px;\n"
"            display: none;\n"
"        }\n"
"        .status.info { background: #ebf8ff; color: #2c5282; display: block; }\n"
"        .status.success { background: #c6f6d5; color: #22543d; display: block; }\n"
"        .status.error { background: #fed7d7; color: #742a2a; display: block; }\n"
"        .file-info {\n"
"            background: #f7fafc;\n"
"            padding: 12px;\n"
"            border-radius: 8px;\n"
"            margin-bottom: 15px;\n"
"            font-size: 13px;\n"
"            color: #4a5568;\n"
"            display: none;\n"
"        }\n"
"        .spinner {\n"
"            display: inline-block;\n"
"            width: 14px;\n"
"            height: 14px;\n"
"            border: 2px solid #cbd5e0;\n"
"            border-top-color: #667eea;\n"
"            border-radius: 50%;\n"
"            animation: spin 0.8s linear infinite;\n"
"            margin-right: 8px;\n"
"        }\n"
"        @keyframes spin { to { transform: rotate(360deg); } }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <div class=\"container\">\n"
"        <h1>🚀 ESP32 OTA Update</h1>\n"
"        <p class=\"subtitle\">Firmware Update Manager</p>\n"
"        \n"
"        <div class=\"info-box\" id=\"deviceInfo\">\n"
"            <strong>Current Version:</strong> <span id=\"currentVersion\">Loading...</span><br>\n"
"            <strong>Device IP:</strong> <span id=\"deviceIP\">-</span>\n"
"        </div>\n"
"        \n"
"        <div class=\"upload-area\" id=\"uploadArea\">\n"
"            <div class=\"upload-icon\">📦</div>\n"
"            <div class=\"upload-text\">Drag & drop firmware file</div>\n"
"            <div class=\"upload-hint\">or click to browse (.bin files)</div>\n"
"            <input type=\"file\" id=\"fileInput\" accept=\".bin\">\n"
"        </div>\n"
"        \n"
"        <div class=\"file-info\" id=\"fileInfo\"></div>\n"
"        \n"
"        <button class=\"btn\" id=\"uploadBtn\" disabled>Upload Firmware</button>\n"
"        \n"
"        <div class=\"progress-container\" id=\"progressContainer\">\n"
"            <div class=\"progress-bar-bg\">\n"
"                <div class=\"progress-bar\" id=\"progressBar\">0%</div>\n"
"            </div>\n"
"        </div>\n"
"        \n"
"        <div class=\"status\" id=\"status\"></div>\n"
"    </div>\n"
"    \n"
"    <script>\n"
"        const uploadArea = document.getElementById('uploadArea');\n"
"        const fileInput = document.getElementById('fileInput');\n"
"        const uploadBtn = document.getElementById('uploadBtn');\n"
"        const progressContainer = document.getElementById('progressContainer');\n"
"        const progressBar = document.getElementById('progressBar');\n"
"        const status = document.getElementById('status');\n"
"        const fileInfo = document.getElementById('fileInfo');\n"
"        let selectedFile = null;\n"
"        \n"
"        // Load device info\n"
"        fetch('/api/info').then(r => r.json()).then(data => {\n"
"            document.getElementById('currentVersion').textContent = data.version || 'Unknown';\n"
"            document.getElementById('deviceIP').textContent = data.ip || window.location.hostname;\n"
"        }).catch(() => {\n"
"            document.getElementById('deviceIP').textContent = window.location.hostname;\n"
"        });\n"
"        \n"
"        // Click to upload\n"
"        uploadArea.addEventListener('click', () => fileInput.click());\n"
"        \n"
"        // Drag and drop handlers\n"
"        ['dragenter', 'dragover', 'dragleave', 'drop'].forEach(evt => {\n"
"            uploadArea.addEventListener(evt, e => { e.preventDefault(); e.stopPropagation(); });\n"
"        });\n"
"        ['dragenter', 'dragover'].forEach(evt => {\n"
"            uploadArea.addEventListener(evt, () => uploadArea.classList.add('dragover'));\n"
"        });\n"
"        ['dragleave', 'drop'].forEach(evt => {\n"
"            uploadArea.addEventListener(evt, () => uploadArea.classList.remove('dragover'));\n"
"        });\n"
"        uploadArea.addEventListener('drop', e => { handleFile(e.dataTransfer.files[0]); });\n"
"        fileInput.addEventListener('change', e => { handleFile(e.target.files[0]); });\n"
"        \n"
"        function handleFile(file) {\n"
"            if (!file || !file.name.endsWith('.bin')) {\n"
"                showStatus('Please select a .bin firmware file', 'error');\n"
"                return;\n"
"            }\n"
"            selectedFile = file;\n"
"            fileInfo.style.display = 'block';\n"
"            fileInfo.innerHTML = `<strong>Selected:</strong> ${file.name} (${(file.size/1024).toFixed(1)} KB)`;\n"
"            uploadBtn.disabled = false;\n"
"            status.style.display = 'none';\n"
"        }\n"
"        \n"
"        uploadBtn.addEventListener('click', () => {\n"
"            if (!selectedFile) return;\n"
"            uploadFirmware(selectedFile);\n"
"        });\n"
"        \n"
"        function uploadFirmware(file) {\n"
"            const xhr = new XMLHttpRequest();\n"
"            \n"
"            uploadBtn.disabled = true;\n"
"            progressContainer.style.display = 'block';\n"
"            showStatus('<span class=\"spinner\"></span>Uploading firmware...', 'info');\n"
"            \n"
"            xhr.upload.addEventListener('progress', e => {\n"
"                if (e.lengthComputable) {\n"
"                    const pct = Math.round((e.loaded / e.total) * 100);\n"
"                    progressBar.style.width = pct + '%';\n"
"                    progressBar.textContent = pct + '%';\n"
"                }\n"
"            });\n"
"            \n"
"            xhr.addEventListener('load', () => {\n"
"                if (xhr.status === 200) {\n"
"                    showStatus('✓ Firmware uploaded! Verifying signature...', 'info');\n"
"                    setTimeout(() => {\n"
"                        showStatus('✓ Signature valid! Flashing firmware...', 'info');\n"
"                        setTimeout(() => {\n"
"                            showStatus('✓ Update successful! Device rebooting...', 'success');\n"
"                            setTimeout(() => {\n"
"                                showStatus('Waiting for device to come back online...', 'info');\n"
"                            }, 3000);\n"
"                        }, 2000);\n"
"                    }, 1500);\n"
"                } else {\n"
"                    const resp = JSON.parse(xhr.responseText || '{}');\n"
"                    showStatus('✗ Upload failed: ' + (resp.error || 'Unknown error'), 'error');\n"
"                    uploadBtn.disabled = false;\n"
"                }\n"
"            });\n"
"            \n"
"            xhr.addEventListener('error', () => {\n"
"                showStatus('✗ Network error during upload', 'error');\n"
"                uploadBtn.disabled = false;\n"
"            });\n"
"            \n"
"            xhr.open('POST', '/api/update', true);\n"
"            xhr.send(file);\n"
"        }\n"
"        \n"
"        function showStatus(msg, type) {\n"
"            status.className = 'status ' + type;\n"
"            status.innerHTML = msg;\n"
"            status.style.display = 'block';\n"
"        }\n"
"    </script>\n"
"</body>\n"
"</html>\n";

/*******************************************************************************/
/*                     GLOBAL FUNCTION DECLARATIONS                            */
/*******************************************************************************/

#endif /* OTA_WEB_UI_H */
