/******************************************************************************
 * @file ota_public_key.h
 * @brief ECDSA P-256 public key for OTA firmware signature verification
 *
 * @details This file is AUTO-GENERATED by scripts/setup_ota_signing.sh
 *          DO NOT EDIT MANUALLY!
 *
 *          The public key is embedded at compile time and used to verify
 *          firmware signatures during OTA updates. This ensures only
 *          firmware signed with the corresponding private key can be flashed.
 *
 *          Key format: Uncompressed ECDSA P-256 point (65 bytes)
 *          - Byte 0: 0x04 (uncompressed point indicator)
 *          - Bytes 1-32: X coordinate
 *          - Bytes 33-64: Y coordinate
 *
 *          Regenerate keys: ./scripts/setup_ota_signing.sh
 *
 ******************************************************************************/

#ifndef OTA_PUBLIC_KEY_H
#define OTA_PUBLIC_KEY_H

#include <stdint.h>

/**
 * @brief ECDSA P-256 public key for firmware signature verification
 * 
 * This key corresponds to the private key in ota_private_key.pem
 * (which MUST be kept secret and never committed to version control).
 */
static const uint8_t g_ota_public_key[65] = {
    0x04, 0x4f, 0xf7, 0xb3, 0x03, 0xd8, 0x30, 0xe0,
    0xc6, 0xa4, 0x4e, 0x3e, 0x84, 0x27, 0x53, 0x25,
    0xf5, 0x36, 0xda, 0x63, 0xd5, 0x09, 0xa3, 0x05,
    0x7d, 0x09, 0x1f, 0x6e, 0x9a, 0xf7, 0x91, 0x17,
    0x6c, 0x73, 0xe6, 0x18, 0x5b, 0xbb, 0x72, 0xe1,
    0x3d, 0xc6, 0x15, 0xff, 0xa7, 0x37, 0x73, 0xc4,
    0xea, 0xc7, 0x80, 0xc2, 0x02, 0x8a, 0xb8, 0x67,
    0x1d, 0x2f, 0xbe, 0x38, 0xcb, 0x47, 0xf2, 0x5c,
    0xc1
};

#endif /* OTA_PUBLIC_KEY_H */
