/******************************************************************************
 * @file ota_signature.c
 * @brief ECDSA P-256 firmware signature verification implementation
 *
 ******************************************************************************/

/*******************************************************************************/
/*                                 INCLUDES                                    */
/*******************************************************************************/
#include "ota_signature.h"
#include "esp_log.h"
#include "mbedtls/ecdsa.h"
#include "mbedtls/sha256.h"
#include "mbedtls/pk.h"
#include "mbedtls/ecp.h"
#include "mbedtls/error.h"
#include "mbedtls/bignum.h"
#include <string.h>

/*******************************************************************************/
/*                                  MACROS                                     */
/*******************************************************************************/
#define TAG "OTA_SIGNATURE"

/*******************************************************************************/
/*                                DATA TYPES                                   */
/*******************************************************************************/

/*******************************************************************************/
/*                     GLOBAL FUNCTION DECLARATIONS                            */
/*******************************************************************************/

/*******************************************************************************/
/*                     GLOBAL VARIABLES DECLARATIONS                           */
/*******************************************************************************/

/*******************************************************************************/
/*                     GLOBAL VARIABLES DEFINITIONS                            */
/*******************************************************************************/

/*******************************************************************************/
/*                     STATIC FUNCTION DECLARATIONS                            */
/*******************************************************************************/

/*******************************************************************************/
/*                             STATIC VARIABLES                                */
/*******************************************************************************/

/**
 * @brief Embedded ECDSA P-256 public key for firmware verification
 * 
 * @details This public key is embedded at compile time and used to verify
 *          firmware signatures. The key is in uncompressed format:
 *          - Byte 0: 0x04 (uncompressed point indicator)
 *          - Bytes 1-32: X coordinate (32 bytes)
 *          - Bytes 33-64: Y coordinate (32 bytes)
 * 
 *          AUTOMATIC GENERATION:
 *          This key is automatically generated by scripts/setup_ota_signing.sh
 *          and embedded into ota_public_key.h during project setup.
 * 
 *          If ota_public_key.h doesn't exist, a placeholder key is used here.
 *          To generate your own key pair:
 *          1. Run: ./scripts/setup_ota_signing.sh
 *          2. This creates ota_private_key.pem (keep secret!)
 *          3. This creates ota_public_key.h (embedded in firmware)
 *          4. Rebuild your project to include the new public key
 * 
 *          SECURITY NOTE:
 *          The public key is NOT secret. It's safe to embed in firmware and
 *          even publish in source code. Only the private key must be protected.
 */
#if __has_include("ota_public_key.h")
    #include "ota_public_key.h"
#else
    /* Placeholder public key (REPLACE WITH YOUR OWN!)
     * This is a dummy key for compilation. Run ./scripts/setup_ota_signing.sh
     * to generate your real key pair. */
    #warning "Using placeholder public key! Run ./scripts/setup_ota_signing.sh to generate real keys"
    static const uint8_t g_ota_public_key[ECDSA_PUBLIC_KEY_SIZE] = {
        0x04, /* Uncompressed point format */
        /* X coordinate (32 bytes) - PLACEHOLDER */
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        /* Y coordinate (32 bytes) - PLACEHOLDER */
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
    };
#endif

/*******************************************************************************/
/*                     GLOBAL FUNCTION DEFINITIONS                             */
/*******************************************************************************/

bool ota_signature_verify(const uint8_t *firmware_data, 
                          size_t firmware_len,
                          const uint8_t *signature)
{
    if (!firmware_data || !signature || firmware_len == 0) 
    {
        ESP_LOGE(TAG, "Invalid arguments for signature verification");
        return false;
    }

    int ret;
    bool is_valid = false;
    
    /* Initialize mbedTLS context structures for ECDSA verification */
    mbedtls_pk_context pk_ctx;
    mbedtls_pk_init(&pk_ctx);
    
    mbedtls_ecp_keypair *ecp_keypair = NULL;
    uint8_t hash[SHA256_HASH_SIZE] = {0};

    /* #01 - Compute SHA-256 hash of firmware data
     * 
     * The signature is computed over the hash, not the raw firmware.
     * This is standard practice because:
     * - Hashing is faster than signing large data
     * - Fixed-size hash regardless of firmware size
     * - SHA-256 provides collision resistance
     */
    ret = mbedtls_sha256(firmware_data, firmware_len, hash, 0);
    if (ret != 0) 
    {
        char err_buf[100];
        mbedtls_strerror(ret, err_buf, sizeof(err_buf));
        ESP_LOGE(TAG, "SHA-256 hashing failed: %s", err_buf);
        goto cleanup;
    }

    ESP_LOGD(TAG, "Computed SHA-256 hash of %zu bytes firmware", firmware_len);

    /* #02 - Parse public key into mbedTLS PK context
     * 
     * The public key is in raw uncompressed format (0x04 || X || Y).
     * We need to convert it to mbedTLS's internal representation.
     * 
     * Note: We use mbedtls_pk_parse_public_key for PEM format, but our key
     * is in raw binary. We'll manually load it into an ECP keypair instead.
     */
    
    /* Setup PK context for ECDSA */
    ret = mbedtls_pk_setup(&pk_ctx, mbedtls_pk_info_from_type(MBEDTLS_PK_ECKEY));
    if (ret != 0) 
    {
        char err_buf[100];
        mbedtls_strerror(ret, err_buf, sizeof(err_buf));
        ESP_LOGE(TAG, "PK setup failed: %s", err_buf);
        goto cleanup;
    }

    /* Get ECP keypair from PK context */
    ecp_keypair = mbedtls_pk_ec(pk_ctx);
    if (!ecp_keypair) 
    {
        ESP_LOGE(TAG, "Failed to get ECP keypair from PK context");
        goto cleanup;
    }

    /* Load secp256r1 (P-256) curve parameters */
    ret = mbedtls_ecp_group_load(&ecp_keypair->MBEDTLS_PRIVATE(grp), MBEDTLS_ECP_DP_SECP256R1);
    if (ret != 0) 
    {
        char err_buf[100];
        mbedtls_strerror(ret, err_buf, sizeof(err_buf));
        ESP_LOGE(TAG, "Failed to load P-256 curve: %s", err_buf);
        goto cleanup;
    }

    /* Load public key point from raw bytes (uncompressed format: 0x04 || X || Y) */
    ret = mbedtls_ecp_point_read_binary(&ecp_keypair->MBEDTLS_PRIVATE(grp), 
                                         &ecp_keypair->MBEDTLS_PRIVATE(Q),
                                         g_ota_public_key, 
                                         ECDSA_PUBLIC_KEY_SIZE);
    if (ret != 0) 
    {
        char err_buf[100];
        mbedtls_strerror(ret, err_buf, sizeof(err_buf));
        ESP_LOGE(TAG, "Failed to load public key: %s", err_buf);
        goto cleanup;
    }

    ESP_LOGD(TAG, "Public key loaded successfully");

    /* #03 - Verify ECDSA signature
     * 
     * Signature format: 64 bytes (r || s), where r and s are 32-byte integers
     * The signature is verified against the hash using the public key.
     * 
     * Mathematical verification:
     * Given signature (r, s) and hash H:
     * 1. Compute u1 = H * s^-1 mod n
     * 2. Compute u2 = r * s^-1 mod n
     * 3. Compute point P = u1*G + u2*Q (where G is generator, Q is public key)
     * 4. Signature is valid if P.x == r
     * 
     * mbedtls_pk_verify does all this internally.
     */
    ret = mbedtls_pk_verify(&pk_ctx, 
                            MBEDTLS_MD_SHA256,
                            hash, 
                            SHA256_HASH_SIZE,
                            signature, 
                            ECDSA_SIGNATURE_SIZE);
    
    if (ret == 0) 
    {
        /* Signature verification succeeded */
        ESP_LOGI(TAG, "✓ Firmware signature is VALID");
        is_valid = true;
    } 
    else if (ret == MBEDTLS_ERR_ECP_VERIFY_FAILED) 
    {
        /* Signature verification failed (wrong signature or tampered firmware) */
        ESP_LOGW(TAG, "✗ Firmware signature is INVALID (verification failed)");
        is_valid = false;
    } 
    else 
    {
        /* Other error during verification process */
        char err_buf[100];
        mbedtls_strerror(ret, err_buf, sizeof(err_buf));
        ESP_LOGE(TAG, "Signature verification error: %s", err_buf);
        is_valid = false;
    }

cleanup:
    /* #04 - Clean up mbedTLS context (release memory) */
    mbedtls_pk_free(&pk_ctx);
    
    return is_valid;
}

bool ota_signature_verify_hash(const uint8_t *firmware_hash,
                               size_t hash_len,
                               const uint8_t *signature)
{
    if (!firmware_hash || !signature || hash_len != SHA256_HASH_SIZE) 
    {
        ESP_LOGE(TAG, "Invalid arguments for hash signature verification");
        return false;
    }

    int ret;
    mbedtls_ecdsa_context ecdsa;
    mbedtls_mpi r, s;
    
    mbedtls_ecdsa_init(&ecdsa);
    mbedtls_mpi_init(&r);
    mbedtls_mpi_init(&s);

    ESP_LOGD(TAG, "Verifying ECDSA P-256 signature (raw R+S format)...");

    /* #01 - Load P-256 curve */
    ret = mbedtls_ecp_group_load(&ecdsa.MBEDTLS_PRIVATE(grp), MBEDTLS_ECP_DP_SECP256R1);
    if (ret != 0) 
    {
        char err_buf[100];
        mbedtls_strerror(ret, err_buf, sizeof(err_buf));
        ESP_LOGE(TAG, "Failed to load P-256 curve: %s", err_buf);
        goto cleanup;
    }

    /* #02 - Load public key point (uncompressed format: 0x04 || X || Y) */
    ret = mbedtls_ecp_point_read_binary(&ecdsa.MBEDTLS_PRIVATE(grp), 
                                         &ecdsa.MBEDTLS_PRIVATE(Q),
                                         g_ota_public_key, 
                                         ECDSA_PUBLIC_KEY_SIZE);
    if (ret != 0) 
    {
        char err_buf[100];
        mbedtls_strerror(ret, err_buf, sizeof(err_buf));
        ESP_LOGE(TAG, "Failed to load public key: %s", err_buf);
        goto cleanup;
    }

    ESP_LOGD(TAG, "Public key loaded successfully");

    /* #03 - Parse signature (R and S are 32 bytes each in raw format) */
    ret = mbedtls_mpi_read_binary(&r, signature, 32);
    if (ret != 0) 
    {
        char err_buf[100];
        mbedtls_strerror(ret, err_buf, sizeof(err_buf));
        ESP_LOGE(TAG, "Failed to parse signature R: %s", err_buf);
        goto cleanup;
    }

    ret = mbedtls_mpi_read_binary(&s, signature + 32, 32);
    if (ret != 0) 
    {
        char err_buf[100];
        mbedtls_strerror(ret, err_buf, sizeof(err_buf));
        ESP_LOGE(TAG, "Failed to parse signature S: %s", err_buf);
        goto cleanup;
    }

    ESP_LOGD(TAG, "Signature R+S parsed successfully");

    /* #04 - Verify signature against hash */
    ret = mbedtls_ecdsa_verify(&ecdsa.MBEDTLS_PRIVATE(grp),
                                firmware_hash, hash_len,
                                &ecdsa.MBEDTLS_PRIVATE(Q),
                                &r, &s);

    if (ret == 0) 
    {
        ESP_LOGD(TAG, "✓ Signature verification PASSED");
        mbedtls_mpi_free(&r);
        mbedtls_mpi_free(&s);
        mbedtls_ecdsa_free(&ecdsa);
        return true;
    } 
    else 
    {
        char err_buf[100];
        mbedtls_strerror(ret, err_buf, sizeof(err_buf));
        ESP_LOGE(TAG, "Signature verification FAILED: %s", err_buf);
    }

cleanup:
    mbedtls_mpi_free(&r);
    mbedtls_mpi_free(&s);
    mbedtls_ecdsa_free(&ecdsa);
    
    return false;
}

esp_err_t ota_signature_extract(const uint8_t *signed_firmware,
                                size_t signed_len,
                                const uint8_t **firmware_data,
                                size_t *firmware_len,
                                const uint8_t **signature)
{
    /* #01 - Validate input parameters */
    if (!signed_firmware || !firmware_data || !firmware_len || !signature) 
    {
        ESP_LOGE(TAG, "NULL pointer passed to signature extraction");
        return ESP_ERR_INVALID_ARG;
    }

    if (signed_len <= ECDSA_SIGNATURE_SIZE) 
    {
        ESP_LOGE(TAG, "Signed firmware too small (%zu bytes, need > %d)", 
                 signed_len, ECDSA_SIGNATURE_SIZE);
        return ESP_ERR_INVALID_ARG;
    }

    /* #02 - Split signed firmware into firmware portion and signature portion
     * 
     * Signed firmware format:
     * [Firmware Bytes...] [64-byte Signature]
     * 
     * We extract:
     * - firmware_data: Points to beginning of buffer
     * - firmware_len: Total length minus signature size
     * - signature: Points to last 64 bytes of buffer
     */
    *firmware_data = signed_firmware;
    *firmware_len = signed_len - ECDSA_SIGNATURE_SIZE;
    *signature = signed_firmware + *firmware_len;

    ESP_LOGD(TAG, "Extracted: firmware=%zu bytes, signature=%d bytes", 
             *firmware_len, ECDSA_SIGNATURE_SIZE);

    return ESP_OK;
}

/*******************************************************************************/
/*                     STATIC FUNCTION DEFINITIONS                             */
/*******************************************************************************/
